spring:
    application:
        name: auth-server

server:
    port: 9000

logging:
    level:
        root: INFO
        '[org.springframework.security]': INFO
        '[com.luminatask.auth_server]': DEBUG